name: 'DockAI - AI Dockerfile Generation Framework'
description: 'The Customizable AI Framework that generates, validates, and optimizes production-ready Dockerfiles.'
author: 'DockAI Team'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  # LLM Provider Configuration
  llm_provider:
    description: 'LLM provider to use (openai, azure, gemini, anthropic)'
    required: false
    default: 'openai'
  openai_api_key:
    description: 'OpenAI API Key (required for openai provider)'
    required: false
  azure_openai_api_key:
    description: 'Azure OpenAI API Key (required for azure provider)'
    required: false
  azure_openai_endpoint:
    description: 'Azure OpenAI endpoint URL (required for azure provider)'
    required: false
  azure_openai_api_version:
    description: 'Azure OpenAI API version'
    required: false
    default: '2024-02-15-preview'
  google_api_key:
    description: 'Google API Key (required for gemini provider)'
    required: false
  anthropic_api_key:
    description: 'Anthropic API Key (required for anthropic provider)'
    required: false
  project_path:
    description: 'Path to the project to dockerize'
    required: false
    default: '.'
  
  # Per-Agent Model Configuration
  model_analyzer:
    description: 'Model for analyzer agent (default: gpt-4o-mini for openai, gemini-1.5-flash for gemini)'
    required: false
    default: ''
  model_planner:
    description: 'Model for planner agent'
    required: false
    default: ''
  model_generator:
    description: 'Model for generator agent (default: gpt-4o for openai, gemini-1.5-pro for gemini)'
    required: false
    default: ''
  model_generator_iterative:
    description: 'Model for iterative generator agent'
    required: false
    default: ''
  model_reviewer:
    description: 'Model for security reviewer agent'
    required: false
    default: ''
  model_reflector:
    description: 'Model for failure reflection agent'
    required: false
    default: ''
  model_health_detector:
    description: 'Model for health endpoint detection agent'
    required: false
    default: ''
  model_readiness_detector:
    description: 'Model for readiness pattern detection agent'
    required: false
    default: ''
  model_error_analyzer:
    description: 'Model for error classification agent'
    required: false
    default: ''
  model_iterative_improver:
    description: 'Model for iterative improvement agent'
    required: false
    default: ''
  
  # General Settings
  max_retries:
    description: 'Max attempts to fix a failing Dockerfile'
    required: false
    default: '3'
  skip_security_scan:
    description: 'Skip Trivy security scan (true/false)'
    required: false
    default: 'false'
  strict_security:
    description: 'Fail on any vulnerability (true/false)'
    required: false
    default: 'false'
  max_image_size_mb:
    description: 'Max image size in MB (0 to disable)'
    required: false
    default: '500'
  skip_health_check:
    description: 'Skip health checks during validation (true/false)'
    required: false
    default: 'false'
  validation_memory:
    description: 'Memory limit for container validation (e.g., 512m, 1g)'
    required: false
    default: '512m'
  validation_cpus:
    description: 'CPU limit for container validation'
    required: false
    default: '1.0'
  validation_pids:
    description: 'Max processes for container validation'
    required: false
    default: '100'
  analyzer_instructions:
    description: 'Custom instructions for the analyzer (project discovery agent)'
    required: false
    default: ''
  generator_instructions:
    description: 'Custom instructions for the generator (Dockerfile creation agent)'
    required: false
    default: ''
  # Additional Custom Instructions (all agents)
  planner_instructions:
    description: 'Custom instructions for the planner (strategic thinking agent)'
    required: false
    default: ''
  generator_iterative_instructions:
    description: 'Custom instructions for iterative improvement (debugging agent)'
    required: false
    default: ''
  reviewer_instructions:
    description: 'Custom instructions for security review (auditor agent)'
    required: false
    default: ''
  reflector_instructions:
    description: 'Custom instructions for failure analysis (detective agent)'
    required: false
    default: ''
  health_detector_instructions:
    description: 'Custom instructions for health endpoint discovery agent'
    required: false
    default: ''
  readiness_detector_instructions:
    description: 'Custom instructions for readiness pattern analysis agent'
    required: false
    default: ''
  error_analyzer_instructions:
    description: 'Custom instructions for error classification (troubleshooter agent)'
    required: false
    default: ''
  iterative_improver_instructions:
    description: 'Custom instructions for applying fixes (surgical fix agent)'
    required: false
    default: ''
  # Custom AI Prompts (Advanced - Complete Replacement)
  prompt_analyzer:
    description: 'Custom prompt - project discovery and deduction agent'
    required: false
    default: ''
  prompt_planner:
    description: 'Custom prompt - strategic planning agent (chess grandmaster)'
    required: false
    default: ''
  prompt_generator:
    description: 'Custom prompt - Dockerfile reasoning and creation agent'
    required: false
    default: ''
  prompt_generator_iterative:
    description: 'Custom prompt - debugging and surgical fix agent'
    required: false
    default: ''
  prompt_reviewer:
    description: 'Custom prompt - security auditor and threat analysis agent'
    required: false
    default: ''
  prompt_reflector:
    description: 'Custom prompt - detective and post-mortem analysis agent'
    required: false
    default: ''
  prompt_health_detector:
    description: 'Custom prompt - evidence-based health endpoint discovery agent'
    required: false
    default: ''
  prompt_readiness_detector:
    description: 'Custom prompt - behavioral startup pattern analysis agent'
    required: false
    default: ''
  prompt_error_analyzer:
    description: 'Custom prompt - troubleshooter and error classification agent'
    required: false
    default: ''
  prompt_iterative_improver:
    description: 'Custom prompt - surgeon for precise corrections agent'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install DockAI
      shell: bash
      run: pip install dockai-cli

    - name: Run DockAI Framework
      shell: bash
      env:
        # LLM Provider Configuration
        DOCKAI_LLM_PROVIDER: ${{ inputs.llm_provider }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        AZURE_OPENAI_API_KEY: ${{ inputs.azure_openai_api_key }}
        AZURE_OPENAI_ENDPOINT: ${{ inputs.azure_openai_endpoint }}
        AZURE_OPENAI_API_VERSION: ${{ inputs.azure_openai_api_version }}
        GOOGLE_API_KEY: ${{ inputs.google_api_key }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        # Per-Agent Model Configuration
        DOCKAI_MODEL_ANALYZER: ${{ inputs.model_analyzer }}
        DOCKAI_MODEL_PLANNER: ${{ inputs.model_planner }}
        DOCKAI_MODEL_GENERATOR: ${{ inputs.model_generator }}
        DOCKAI_MODEL_GENERATOR_ITERATIVE: ${{ inputs.model_generator_iterative }}
        DOCKAI_MODEL_REVIEWER: ${{ inputs.model_reviewer }}
        DOCKAI_MODEL_REFLECTOR: ${{ inputs.model_reflector }}
        DOCKAI_MODEL_HEALTH_DETECTOR: ${{ inputs.model_health_detector }}
        DOCKAI_MODEL_READINESS_DETECTOR: ${{ inputs.model_readiness_detector }}
        DOCKAI_MODEL_ERROR_ANALYZER: ${{ inputs.model_error_analyzer }}
        DOCKAI_MODEL_ITERATIVE_IMPROVER: ${{ inputs.model_iterative_improver }}
        # Legacy model env vars (for backward compatibility)
        MODEL_GENERATOR: ${{ inputs.model_generator }}
        MODEL_ANALYZER: ${{ inputs.model_analyzer }}
        # General Settings
        MAX_RETRIES: ${{ inputs.max_retries }}
        DOCKAI_SKIP_SECURITY_SCAN: ${{ inputs.skip_security_scan }}
        DOCKAI_STRICT_SECURITY: ${{ inputs.strict_security }}
        DOCKAI_MAX_IMAGE_SIZE_MB: ${{ inputs.max_image_size_mb }}
        DOCKAI_SKIP_HEALTH_CHECK: ${{ inputs.skip_health_check }}
        DOCKAI_VALIDATION_MEMORY: ${{ inputs.validation_memory }}
        DOCKAI_VALIDATION_CPUS: ${{ inputs.validation_cpus }}
        DOCKAI_VALIDATION_PIDS: ${{ inputs.validation_pids }}
        # Custom Instructions
        DOCKAI_ANALYZER_INSTRUCTIONS: ${{ inputs.analyzer_instructions }}
        DOCKAI_GENERATOR_INSTRUCTIONS: ${{ inputs.generator_instructions }}
        DOCKAI_PLANNER_INSTRUCTIONS: ${{ inputs.planner_instructions }}
        DOCKAI_GENERATOR_ITERATIVE_INSTRUCTIONS: ${{ inputs.generator_iterative_instructions }}
        DOCKAI_REVIEWER_INSTRUCTIONS: ${{ inputs.reviewer_instructions }}
        DOCKAI_REFLECTOR_INSTRUCTIONS: ${{ inputs.reflector_instructions }}
        DOCKAI_HEALTH_DETECTOR_INSTRUCTIONS: ${{ inputs.health_detector_instructions }}
        DOCKAI_READINESS_DETECTOR_INSTRUCTIONS: ${{ inputs.readiness_detector_instructions }}
        DOCKAI_ERROR_ANALYZER_INSTRUCTIONS: ${{ inputs.error_analyzer_instructions }}
        DOCKAI_ITERATIVE_IMPROVER_INSTRUCTIONS: ${{ inputs.iterative_improver_instructions }}
        # Custom Prompts
        DOCKAI_PROMPT_ANALYZER: ${{ inputs.prompt_analyzer }}
        DOCKAI_PROMPT_PLANNER: ${{ inputs.prompt_planner }}
        DOCKAI_PROMPT_GENERATOR: ${{ inputs.prompt_generator }}
        DOCKAI_PROMPT_GENERATOR_ITERATIVE: ${{ inputs.prompt_generator_iterative }}
        DOCKAI_PROMPT_REVIEWER: ${{ inputs.prompt_reviewer }}
        DOCKAI_PROMPT_REFLECTOR: ${{ inputs.prompt_reflector }}
        DOCKAI_PROMPT_HEALTH_DETECTOR: ${{ inputs.prompt_health_detector }}
        DOCKAI_PROMPT_READINESS_DETECTOR: ${{ inputs.prompt_readiness_detector }}
        DOCKAI_PROMPT_ERROR_ANALYZER: ${{ inputs.prompt_error_analyzer }}
        DOCKAI_PROMPT_ITERATIVE_IMPROVER: ${{ inputs.prompt_iterative_improver }}
      run: |
        echo "🐳 Starting DockAI Framework..."
        dockai build ${{ inputs.project_path }} --no-cache
