name: 'DockAI - Universal DevOps Architect'
description: 'Autonomously generate, validate, and build production-ready Dockerfiles using AI.'
author: 'DockAI Team'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  openai_api_key:
    description: 'OpenAI API Key for the AI agent'
    required: true
  project_path:
    description: 'Path to the project to dockerize'
    required: false
    default: '.'
  model_generator:
    description: 'Model for generation/reflection (default: gpt-4o)'
    required: false
    default: 'gpt-4o'
  model_analyzer:
    description: 'Model for analysis/planning (default: gpt-4o-mini)'
    required: false
    default: 'gpt-4o-mini'
  max_retries:
    description: 'Max attempts to fix a failing Dockerfile'
    required: false
    default: '3'
  skip_security_scan:
    description: 'Skip Trivy security scan (true/false)'
    required: false
    default: 'false'
  strict_security:
    description: 'Fail on any vulnerability (true/false)'
    required: false
    default: 'false'
  max_image_size_mb:
    description: 'Max image size in MB (0 to disable)'
    required: false
    default: '500'
  skip_health_check:
    description: 'Skip health checks during validation (true/false)'
    required: false
    default: 'false'
  validation_memory:
    description: 'Memory limit for container validation (e.g., 512m, 1g)'
    required: false
    default: '512m'
  validation_cpus:
    description: 'CPU limit for container validation'
    required: false
    default: '1.0'
  validation_pids:
    description: 'Max processes for container validation'
    required: false
    default: '100'
  analyzer_instructions:
    description: 'Custom instructions for the analyzer phase'
    required: false
    default: ''
  generator_instructions:
    description: 'Custom instructions for the generator phase'
    required: false
    default: ''
  # Additional Custom Instructions (all phases)
  planner_instructions:
    description: 'Custom instructions for the planner phase'
    required: false
    default: ''
  generator_iterative_instructions:
    description: 'Custom instructions for iterative Dockerfile improvement'
    required: false
    default: ''
  reviewer_instructions:
    description: 'Custom instructions for security review'
    required: false
    default: ''
  reflector_instructions:
    description: 'Custom instructions for failure analysis'
    required: false
    default: ''
  health_detector_instructions:
    description: 'Custom instructions for health endpoint detection'
    required: false
    default: ''
  readiness_detector_instructions:
    description: 'Custom instructions for readiness pattern detection'
    required: false
    default: ''
  error_analyzer_instructions:
    description: 'Custom instructions for error classification'
    required: false
    default: ''
  iterative_improver_instructions:
    description: 'Custom instructions for applying fixes'
    required: false
    default: ''
  # Custom AI Prompts (Advanced - Complete Replacement)
  prompt_analyzer:
    description: 'Custom prompt for the Build Engineer (project analysis)'
    required: false
    default: ''
  prompt_planner:
    description: 'Custom prompt for the DevOps Architect (build planning)'
    required: false
    default: ''
  prompt_generator:
    description: 'Custom prompt for the Docker Architect (Dockerfile generation)'
    required: false
    default: ''
  prompt_generator_iterative:
    description: 'Custom prompt for the Docker Engineer (iterative improvement)'
    required: false
    default: ''
  prompt_reviewer:
    description: 'Custom prompt for the Security Engineer (security review)'
    required: false
    default: ''
  prompt_reflector:
    description: 'Custom prompt for the Principal DevOps Engineer (failure analysis)'
    required: false
    default: ''
  prompt_health_detector:
    description: 'Custom prompt for the Code Analyst (health endpoint detection)'
    required: false
    default: ''
  prompt_readiness_detector:
    description: 'Custom prompt for the Startup Expert (readiness pattern detection)'
    required: false
    default: ''
  prompt_error_analyzer:
    description: 'Custom prompt for the DevOps Engineer (error classification)'
    required: false
    default: ''
  prompt_iterative_improver:
    description: 'Custom prompt for the Senior Docker Engineer (applying fixes)'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install DockAI
      shell: bash
      run: pip install dockai-cli

    - name: Run DockAI Agent
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        MODEL_GENERATOR: ${{ inputs.model_generator }}
        MODEL_ANALYZER: ${{ inputs.model_analyzer }}
        MAX_RETRIES: ${{ inputs.max_retries }}
        DOCKAI_SKIP_SECURITY_SCAN: ${{ inputs.skip_security_scan }}
        DOCKAI_STRICT_SECURITY: ${{ inputs.strict_security }}
        DOCKAI_MAX_IMAGE_SIZE_MB: ${{ inputs.max_image_size_mb }}
        DOCKAI_SKIP_HEALTH_CHECK: ${{ inputs.skip_health_check }}
        DOCKAI_VALIDATION_MEMORY: ${{ inputs.validation_memory }}
        DOCKAI_VALIDATION_CPUS: ${{ inputs.validation_cpus }}
        DOCKAI_VALIDATION_PIDS: ${{ inputs.validation_pids }}
        DOCKAI_ANALYZER_INSTRUCTIONS: ${{ inputs.analyzer_instructions }}
        DOCKAI_GENERATOR_INSTRUCTIONS: ${{ inputs.generator_instructions }}
        DOCKAI_PLANNER_INSTRUCTIONS: ${{ inputs.planner_instructions }}
        DOCKAI_GENERATOR_ITERATIVE_INSTRUCTIONS: ${{ inputs.generator_iterative_instructions }}
        DOCKAI_REVIEWER_INSTRUCTIONS: ${{ inputs.reviewer_instructions }}
        DOCKAI_REFLECTOR_INSTRUCTIONS: ${{ inputs.reflector_instructions }}
        DOCKAI_HEALTH_DETECTOR_INSTRUCTIONS: ${{ inputs.health_detector_instructions }}
        DOCKAI_READINESS_DETECTOR_INSTRUCTIONS: ${{ inputs.readiness_detector_instructions }}
        DOCKAI_ERROR_ANALYZER_INSTRUCTIONS: ${{ inputs.error_analyzer_instructions }}
        DOCKAI_ITERATIVE_IMPROVER_INSTRUCTIONS: ${{ inputs.iterative_improver_instructions }}
        DOCKAI_PROMPT_ANALYZER: ${{ inputs.prompt_analyzer }}
        DOCKAI_PROMPT_PLANNER: ${{ inputs.prompt_planner }}
        DOCKAI_PROMPT_GENERATOR: ${{ inputs.prompt_generator }}
        DOCKAI_PROMPT_GENERATOR_ITERATIVE: ${{ inputs.prompt_generator_iterative }}
        DOCKAI_PROMPT_REVIEWER: ${{ inputs.prompt_reviewer }}
        DOCKAI_PROMPT_REFLECTOR: ${{ inputs.prompt_reflector }}
        DOCKAI_PROMPT_HEALTH_DETECTOR: ${{ inputs.prompt_health_detector }}
        DOCKAI_PROMPT_READINESS_DETECTOR: ${{ inputs.prompt_readiness_detector }}
        DOCKAI_PROMPT_ERROR_ANALYZER: ${{ inputs.prompt_error_analyzer }}
        DOCKAI_PROMPT_ITERATIVE_IMPROVER: ${{ inputs.prompt_iterative_improver }}
      run: |
        echo "🐳 Starting DockAI Agent..."
        dockai build ${{ inputs.project_path }} --no-cache
