name: 'DockAI - Universal DevOps Architect'
description: 'Autonomously generate, validate, and build production-ready Dockerfiles using AI.'
author: 'DockAI Team'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  openai_api_key:
    description: 'OpenAI API Key for the AI agent'
    required: true
  project_path:
    description: 'Path to the project to dockerize'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install DockAI
      shell: bash
      run: pip install dockai

    - name: Run DockAI Agent
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
      run: |
        echo "🐳 Starting DockAI Agent..."
        dockai build ${{ inputs.project_path }} --no-cache
