name: 'DockAI - Universal DevOps Architect'
description: 'Autonomously generate, validate, and build production-ready Dockerfiles using AI.'
author: 'DockAI Team'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  openai_api_key:
    description: 'OpenAI API Key for the AI agent'
    required: true
  project_path:
    description: 'Path to the project to dockerize'
    required: false
    default: '.'
  push_image:
    description: 'Whether to push the image to a registry after successful build (true/false)'
    required: false
    default: 'false'
  image_name:
    description: 'Name of the image to build (e.g., myuser/myapp)'
    required: false
    default: 'dockai-app'
  registry_username:
    description: 'Docker Registry Username (required if push_image is true)'
    required: false
  registry_password:
    description: 'Docker Registry Password (required if push_image is true)'
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install DockAI
      shell: bash
      run: pip install dockai

    - name: Run DockAI Agent
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
      run: |
        echo "🐳 Starting DockAI Agent..."
        dockai build ${{ inputs.project_path }} --no-cache

    - name: Login to Docker Registry
      if: inputs.push_image == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: Build and Push Final Image
      if: inputs.push_image == 'true'
      shell: bash
      run: |
        echo "🚀 Building and pushing final image..."
        # DockAI generates the Dockerfile in the project path
        docker build -t ${{ inputs.image_name }}:latest ${{ inputs.project_path }}
        docker push ${{ inputs.image_name }}:latest
        echo "✅ Image pushed to ${{ inputs.image_name }}:latest"
