name: 'DockAI - Dockerfile Generator'
description: 'Automatically generate an optimized, production-ready Dockerfile for your repository using AI.'
author: 'Januda Bethmin'
branding:
  icon: 'box'
  color: 'blue'

inputs:
  openai_api_key:
    description: 'Your OpenAI API Key'
    required: true
  path:
    description: 'Path to the repository to analyze (relative to the root)'
    required: false
    default: '.'
  model_analyzer:
    description: 'Model to use for Stage 1 (Analysis)'
    required: true
  model_generator:
    description: 'Model to use for Stage 2 (Generation)'
    required: true
  analyzer_instructions:
    description: 'Optional custom instructions for the analyzer stage'
    required: false
    default: ''
  generator_instructions:
    description: 'Optional custom instructions for the generator stage'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
  env:
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    MODEL_ANALYZER: ${{ inputs.model_analyzer }}
    MODEL_GENERATOR: ${{ inputs.model_generator }}
    DOCKAI_ANALYZER_INSTRUCTIONS: ${{ inputs.analyzer_instructions }}
    DOCKAI_GENERATOR_INSTRUCTIONS: ${{ inputs.generator_instructions }}
