name: 'DockAI - Dockerfile Generator'
description: 'Automatically generate an optimized, production-ready Dockerfile for your repository using AI.'
author: 'Januda Bethmin'
branding:
  icon: 'box'
  color: 'blue'

inputs:
  openai_api_key:
    description: 'Your OpenAI API Key'
    required: true
  path:
    description: 'Path to the repository to analyze (relative to the root)'
    required: false
    default: '.'
  model_analyzer:
    description: 'Model to use for Stage 1 (Analysis)'
    required: true
  model_generator:
    description: 'Model to use for Stage 2 (Generation)'
    required: true
  analyzer_instructions:
    description: 'Optional custom instructions for the analyzer stage'
    required: false
    default: ''
  generator_instructions:
    description: 'Optional custom instructions for the generator stage'
    required: false
    default: ''
  max_retries:
    description: 'Maximum number of retries for self-correction'
    required: false
    default: '3'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install DockAI
      shell: bash
      run: |
        pip install .
        
    - name: Run DockAI
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        MODEL_ANALYZER: ${{ inputs.model_analyzer }}
        MODEL_GENERATOR: ${{ inputs.model_generator }}
        DOCKAI_ANALYZER_INSTRUCTIONS: ${{ inputs.analyzer_instructions }}
        DOCKAI_GENERATOR_INSTRUCTIONS: ${{ inputs.generator_instructions }}
        MAX_RETRIES: ${{ inputs.max_retries }}
      run: |
        dockai "${{ inputs.path }}"
